language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- ./test/shell_scripts/run_tests.sh
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: svzbaqJC/PDr/vWapA0MWOinUX9630FtEyX413r9XoQJuQEptQPcT+rlzPoye2BxTI5Bt13Asl6Ii1o1JSiRzB3K8M6BweMOOxhDuqKcoLC8wVhbtBI190mT+qQoJFvIZoELRPeEU6ftbHxhcC0nf/WeKmJP7eiYTo2KTxduAgTP/KheIEXovJEcb854pWC4MjbgAn5AbPlfTJ5+BU6x6a5io4eaUSSJIXdGlMCAn5onoW/4g9r857zMlE0c11eN1hcpLJcX8nsf2GBJ+DGujPgiDBcBMbXl8SX8r+Sf+yKKP8v2dbfwauBw2vcNjK+bAiFu9oQfNHj2h4SDnr7nb2WTHqiVHt+TNPni5DgE59U6a/x6LZm151cVekCuFMtTzxkX5xcIeQQpM1loYBi+IZvRtao5li5DUYfzphCej6I+8IW/DTrx7ScaSnTrsoS2emqucWEjCTmQK6ZrWtxOKiOxxiNK1EU4o/0yMECS1aWdhUYP66Kjv9VliENJkO8baXSoe02dfB+DSngJYVZBij0YIMY0BN406XePhYoOAKJhUusQx8DI9Me94mdoexbpa7yTFrnOpLjrfGuoSGNoZsSJpy0rk24cSTUY8WIMLi/NswnpKCUVpW4tbq+mRHUH26wkqKopkwBovPEA4IG3pZnSwvN3dHMIZIqKmUQCze4=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iN5Q/jPYCBewprie+HEYzpAqzbl+3nx/+m8opHpeGXzLfviKCaOcs9V2/qNE6VQHLSijL7ORdkJ68pnKJdqba8o/ZVkCYTh66Ma0KsHppYW2M/qcQqqYed+v8+3QP8cYIJ1CvrmSN8ydq3Z6fE4C9DjwEbTtpjtUTtJoTA06V0DjWUDunUppJpmjS55zCOrGr5Oc5yuSxv9mIm4zDgfunFMGWh5NHwaevZHKMzCNFiT1moPpjfpVDb+WTZv6oM8oTpezYrix+qQlanBHGcbqnluwQSSR3IwU5q3n1c6mfy7jiVcj5Or2RVzPB2ZYuzlkDHnrxPJA2LLcgiy3YM0/cRdtPocIey3VmR8wXw3zvzkp9AiM+z+pOL7a5mVZbh0ytZB/4P0s/VhRCJvvl3EK54Z+J0m+o9iKD2mffqkjrQKURHeR25cipasRCfzwesBLAvfXchau6InqW6a05s+VrpDYH9UXdMXWVYLRYiL/3FbTqo1I0LlzLARSSnq/YMU/5TV8yMlIvN5VoWWU+HeSCv8A6WP8SJvUWyL1xghCNJ8vv8QaZusWwM8d2rAuRCw978mvnSuV+ShSiU0zOWwyfmyRKZQghlnT6M8LeJcPOmbOIE8+5GznZh9hlF7ZM1I6CRD8Un4HHltwu2Egqem/rSYZR5/GifOqnsY/hGwb5+E=
