language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: SAmbf91Qf8QocNV3+KgI/Slg3qgrEF/+Csmprb2azG5BgLy12LC8M2eyOwAbhXGHsNUNZVoE0OjwDXFBa1I/TRYVHlLQWpFDsdPFmchbDZvCTWAoSRobnanWHltofLNqrp5/GLVAKsJ7WPomt3l0XdLSdylIWtMzK18DlpFNoi2JO8VCy+XsxqOXy7ChqtzRJhGtGpvfCilSJA5pvQSLgDXv+LA0oymGIXNCUgDEIRC/IES0k1EpGJh3urBkSW0443Rul45B1ZukTUY243gNJmI+wS7K42hRkXRIF/ICzgcC4ijy3sQ35O1vtkPTmTdmtCPUbjwlnmWQL+R/zwkgNZ2VLaE4LLKgrru1arNAb9SqcSRElJC9AL2IRnzVssVqa7cxjAJ5K0+f6YNCVGlxOBZZ5Ei2CxymOdxf3WnjcG7JSR33rjMod2zHX9jR7C5ZrswpZ4C2LE3MXFodyTYMZiXM+ZSV3U4N+8ybT8YgkD/xNtjCD3IbDvySJwNs5KO2ViDwm6f75Li0g8lJUyABlrHLHCxu7vQCaRlGRCH4v4HyoCAi6L/BWb0zuSkp10ENHG3KD1Y9W2rwaSbrz2bvrR5LN45agQQltWbgbVzqt0I9HccVLdEfR90d2VaN8z/L5kWClvts/tr/LW62Gh90kjCefkWYjAiOrKUO60UqbK0=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iN5Q/jPYCBewprie+HEYzpAqzbl+3nx/+m8opHpeGXzLfviKCaOcs9V2/qNE6VQHLSijL7ORdkJ68pnKJdqba8o/ZVkCYTh66Ma0KsHppYW2M/qcQqqYed+v8+3QP8cYIJ1CvrmSN8ydq3Z6fE4C9DjwEbTtpjtUTtJoTA06V0DjWUDunUppJpmjS55zCOrGr5Oc5yuSxv9mIm4zDgfunFMGWh5NHwaevZHKMzCNFiT1moPpjfpVDb+WTZv6oM8oTpezYrix+qQlanBHGcbqnluwQSSR3IwU5q3n1c6mfy7jiVcj5Or2RVzPB2ZYuzlkDHnrxPJA2LLcgiy3YM0/cRdtPocIey3VmR8wXw3zvzkp9AiM+z+pOL7a5mVZbh0ytZB/4P0s/VhRCJvvl3EK54Z+J0m+o9iKD2mffqkjrQKURHeR25cipasRCfzwesBLAvfXchau6InqW6a05s+VrpDYH9UXdMXWVYLRYiL/3FbTqo1I0LlzLARSSnq/YMU/5TV8yMlIvN5VoWWU+HeSCv8A6WP8SJvUWyL1xghCNJ8vv8QaZusWwM8d2rAuRCw978mvnSuV+ShSiU0zOWwyfmyRKZQghlnT6M8LeJcPOmbOIE8+5GznZh9hlF7ZM1I6CRD8Un4HHltwu2Egqem/rSYZR5/GifOqnsY/hGwb5+E=
