language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: hor+9W5KoZQo4IFZShGhnaDgIYZtgtsCGf9MzB6HSN6I6iidjHwyPa9GDwJFwuqNURuYXYTf10NLatVFETHLXMLyKNLHSHRbMvxei8W9Uwuxi4VlSk4HboLqJPq5ojV7xmSwCgn/2/Rg6U9/wv4Xhx4S3L2iTJYyZc2mEcruIZ6NAyWCMNqsxzMrpNtIGbyOcKD0ZkhQBlE/HrXhFOEDRfK+FxXwqqsSWwCUfa7RAaM/YDBFKxTyv3ep/9CTGAKBxOoJ3kDZ3HKF81Rg7UYwkPqL3Q0v8RZi5GFp4nxRMwKQinEW77u6vOjnhGMnaPsZEPGBcB4jjX6i0HL3rapFbBsxcnPvTWGMenTUfHxglGGH0C/S9Ytb2KZmosky0FriObXJGct5T4GKp8a9ojV0eY9iuvgu1AFVr88Hllhb3iw9EnOoLxuXyLoWPfOoWhxJOn5o9WNOoCbJUgGl2iP0sq3hbEMTUN8fWkuGLm5/0N9OJbtQ3nZraLX7cQ902A/Q9a4tDwYwR4+h2IdbO52zGkK++jffNI0Yry9uxSiY0gOBWF7HdxR9lyUCGDK6b8RtOOJX+xQwHV5Kig/JaFxKG473T4TJjkgSlujmL2P9FD+83a3yCjRIMSlaEbhfpW74T8vbVW7ED3sSnsPYYwYVm81QixMiZY4ulful8GNvAhs=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iN5Q/jPYCBewprie+HEYzpAqzbl+3nx/+m8opHpeGXzLfviKCaOcs9V2/qNE6VQHLSijL7ORdkJ68pnKJdqba8o/ZVkCYTh66Ma0KsHppYW2M/qcQqqYed+v8+3QP8cYIJ1CvrmSN8ydq3Z6fE4C9DjwEbTtpjtUTtJoTA06V0DjWUDunUppJpmjS55zCOrGr5Oc5yuSxv9mIm4zDgfunFMGWh5NHwaevZHKMzCNFiT1moPpjfpVDb+WTZv6oM8oTpezYrix+qQlanBHGcbqnluwQSSR3IwU5q3n1c6mfy7jiVcj5Or2RVzPB2ZYuzlkDHnrxPJA2LLcgiy3YM0/cRdtPocIey3VmR8wXw3zvzkp9AiM+z+pOL7a5mVZbh0ytZB/4P0s/VhRCJvvl3EK54Z+J0m+o9iKD2mffqkjrQKURHeR25cipasRCfzwesBLAvfXchau6InqW6a05s+VrpDYH9UXdMXWVYLRYiL/3FbTqo1I0LlzLARSSnq/YMU/5TV8yMlIvN5VoWWU+HeSCv8A6WP8SJvUWyL1xghCNJ8vv8QaZusWwM8d2rAuRCw978mvnSuV+ShSiU0zOWwyfmyRKZQghlnT6M8LeJcPOmbOIE8+5GznZh9hlF7ZM1I6CRD8Un4HHltwu2Egqem/rSYZR5/GifOqnsY/hGwb5+E=
