language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: n+qPL0Ltb7oUlc69kG1ofZANFLxSxI4PFAS/WpgIzSLGbLeAORwiHn/1KPjqfqNer+7PRztUD9ii40awfO4wJATKXNKojWwYc6p0P5VY8+1ipHxSnEbO/ZifD82Qs9E02r+1ikf/dnNby6WvLO+XGgPY0v0UvSBkaY0OE398JZM9YnqDi0vdFCRtVqHWcelzwuI9YI8atMQ0c3pCzKm8xm/9MvBxYl/ss/6KwMbI3eSC4pV1nvvFogA1Kk8cq/sWOkn8AbsT3jEupzz2N5AB7rh+ogP+g9LttOGepHmZ22Oov30AdtY3TrAI7j8GnzrAKy2MdS1WQNVpQqAJPFHW/51uJTkWA03w1AJDkT83ueEWcRTEesvjdvkQ5OYELxDB+m5LqKO02qDXv0vjnCFTo/jxELQKvySZJiYOlatUaDnN90l0G4vI5DlRtviyrCR5NMhztDF0qRadwvrxKqHr2+2cpc3SSgOF0l3zj5OwGjNvh76ojPOwYV0+UtrslKZfmgVjUSlwlPVGHs25ZKM3Bo6PABRSh4RYsM/RtBcj28Asp9Lkr7pHFdPE+DPIoX6EPQuwjV6K39/B8BqYbgN73i0gXgUuW7Y655tBopBKhdGe6EUN4q3eUOEKtel3xzBUIfJiVveGL2gifqLWh7jNO2woEJhbA3GT2ox5aQtJ//g=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iN5Q/jPYCBewprie+HEYzpAqzbl+3nx/+m8opHpeGXzLfviKCaOcs9V2/qNE6VQHLSijL7ORdkJ68pnKJdqba8o/ZVkCYTh66Ma0KsHppYW2M/qcQqqYed+v8+3QP8cYIJ1CvrmSN8ydq3Z6fE4C9DjwEbTtpjtUTtJoTA06V0DjWUDunUppJpmjS55zCOrGr5Oc5yuSxv9mIm4zDgfunFMGWh5NHwaevZHKMzCNFiT1moPpjfpVDb+WTZv6oM8oTpezYrix+qQlanBHGcbqnluwQSSR3IwU5q3n1c6mfy7jiVcj5Or2RVzPB2ZYuzlkDHnrxPJA2LLcgiy3YM0/cRdtPocIey3VmR8wXw3zvzkp9AiM+z+pOL7a5mVZbh0ytZB/4P0s/VhRCJvvl3EK54Z+J0m+o9iKD2mffqkjrQKURHeR25cipasRCfzwesBLAvfXchau6InqW6a05s+VrpDYH9UXdMXWVYLRYiL/3FbTqo1I0LlzLARSSnq/YMU/5TV8yMlIvN5VoWWU+HeSCv8A6WP8SJvUWyL1xghCNJ8vv8QaZusWwM8d2rAuRCw978mvnSuV+ShSiU0zOWwyfmyRKZQghlnT6M8LeJcPOmbOIE8+5GznZh9hlF7ZM1I6CRD8Un4HHltwu2Egqem/rSYZR5/GifOqnsY/hGwb5+E=
